# Generated by Django 4.2.11 on 2024-03-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesPanelModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=30)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
