# Generated by Django 4.2.11 on 2024-03-26 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208'),
        ('activities_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitieModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='images/')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='activitiespanelmodel',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities_panel.activitiemodel'),
        ),
    ]
